In [1]:
%load_ext autoreload

In [43]:
%autoreload
import os
from sys import path
import re
import pandas as pd
path.append('../..')
import numpy as np
from scipy.stats import ttest_rel
from relation_extraction.data.summarize_semeval2010 import *
output_path = '/scratch/geeticka/relation-extraction/output/semeval2010/CrossValidation'
def res(path): return os.path.join(output_path, path)

relation_full_form_dictionary = {'C-E': 'Cause-Effect', 'C-W': 'Component-Whole', 'C-C': 'Content-Container',
                                 'E-D': 'Entity-Destination', 'E-O': 'Entity-Origin', 'I-A': 'Instrument-Agency',
                                 'M-C': 'Member-Collection', 'M-T': 'Message-Topic', 'P-P': 'Product-Producer',
                                 '_O': 'Other'}
relation_as_short_list = ['C-E', 'C-W', 'C-C', 'E-D', 'E-O', 'I-A', 'M-C', 'M-T', 'P-P', '_O']

# Fold0

We want to print indiv metrics both with and without the other class

In [44]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold0', 'error-analysis/piecewise-pool/Fold0', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -0.46 	 p_value 0.6562784444426755
Metric: Recall 	 statistic 0.09 	 p_value 0.9267797736150227
Metric: F1 	 statistic -0.61 	 p_value 0.559847810389105

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic -0.39 	 p_value 0.7025790358814328
Metric: Recall 	 statistic -0.15 	 p_value 0.8843613333646354
Metric: F1 	 statistic -0.96 	 p_value 0.36177060656445936

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro 0.37
Metric: Recall 	 Macro-Micro -0.77
Metric: F1 	 Macro-Micro -0.47

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro 0.08
Metric: Recall 	 Macro-Micro -0.59
Metric: F1 	 Macro-Micro -0.36

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference -0.34
Metric: Recall 	 Difference 0.12
Metric: F1 	 Difference -0.30

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference -0.63
Metric: Recall 	 Difference 0.30
Metric: F1 	 Difference -0.19
Accuracy_Baseline - Accuracy_Piecewise-Pool -0.25

In [45]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(6) M-T(1) P-P(1) _O(2),2.0,91.0
1,Component-Whole,C-C(1) E-O(2) M-C(1) M-T(2) _O(12),12.0,71.0
2,Content-Container,C-W(2) E-D(4) _O(1),1.0,48.0
3,Entity-Destination,C-C(1),0.0,84.0
4,Entity-Origin,C-W(1) _O(4),4.0,67.0
5,Instrument-Agency,C-W(5) E-O(1) M-T(2) P-P(2) _O(6),6.0,34.0
6,Member-Collection,C-W(2) C-C(2) _O(2),2.0,64.0
7,Message-Topic,C-W(1) E-D(1) P-P(2) _O(8),8.0,50.0
8,Product-Producer,C-E(1) E-D(1) E-O(3) I-A(1) M-C(1) _O(9),9.0,57.0
9,Other,C-E(10) C-W(15) C-C(4) E-D(11) E-O(9) I-A(4) M...,NaN,56.0

In [46]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(4) M-T(1) P-P(1) _O(3),3.0,92.0
1,Component-Whole,C-C(2) I-A(1) M-C(2) M-T(3) _O(12),12.0,70.0
2,Content-Container,C-W(1) E-D(4) _O(4),4.0,46.0
3,Entity-Destination,C-C(2),0.0,83.0
4,Entity-Origin,C-E(2) P-P(2) _O(5),5.0,63.0
5,Instrument-Agency,C-W(4) M-T(2) P-P(2) _O(4),4.0,38.0
6,Member-Collection,C-W(2) C-C(1) _O(4),4.0,63.0
7,Message-Topic,C-W(1) P-P(1) _O(8),8.0,51.0
8,Product-Producer,C-W(1) E-D(1) E-O(2) I-A(2) M-T(1) _O(8),8.0,58.0
9,Other,C-E(11) C-W(13) C-C(2) E-D(10) E-O(10) I-A(4) ...,NaN,60.0

# Fold1

In [47]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold1', 'error-analysis/piecewise-pool/Fold1', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic 0.55 	 p_value 0.595666085917252
Metric: Recall 	 statistic -0.67 	 p_value 0.5246269745913417
Metric: F1 	 statistic -0.07 	 p_value 0.9467399091351281

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic -0.01 	 p_value 0.9946292700927752
Metric: Recall 	 statistic -0.62 	 p_value 0.5527787635864978
Metric: F1 	 statistic -0.27 	 p_value 0.7908246195982223

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.64
Metric: Recall 	 Macro-Micro -0.16
Metric: F1 	 Macro-Micro -0.51

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro -0.62
Metric: Recall 	 Macro-Micro 0.03
Metric: F1 	 Macro-Micro -0.45

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference 0.76
Metric: Recall 	 Difference -1.09
Metric: F1 	 Difference -0.06

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference 0.78
Metric: Recall 	 Difference -0.90
Metric: F1 	 Difference 0.00
Accuracy_Baseline - Accuracy_Piecewise-Pool -0.62

In [48]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(2) I-A(1) P-P(2) _O(5),5.0,90.0
1,Component-Whole,C-C(2) I-A(2) M-C(2) M-T(3) P-P(1) _O(13),13.0,69.0
2,Content-Container,E-D(1) M-C(2) _O(1),1.0,51.0
3,Entity-Destination,C-C(7) _O(3),3.0,75.0
4,Entity-Origin,C-E(1) C-W(1) I-A(1) P-P(2) _O(3),3.0,64.0
5,Instrument-Agency,C-W(2) P-P(3) _O(10),10.0,36.0
6,Member-Collection,C-W(2) C-C(1) E-O(1) M-T(1) _O(5),5.0,58.0
7,Message-Topic,C-E(1) C-W(1) E-D(2) _O(6),6.0,54.0
8,Product-Producer,C-E(1) C-C(1) E-D(1) E-O(6) I-A(2) _O(8),8.0,53.0
9,Other,C-E(10) C-W(14) C-C(4) E-D(10) E-O(14) I-A(13)...,NaN,44.0

In [49]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(2) I-A(1) M-T(1) P-P(1) _O(6),6.0,90.0
1,Component-Whole,C-E(1) C-C(3) E-D(1) I-A(2) M-C(2) M-T(5) P-P(...,8.0,69.0
2,Content-Container,E-D(1) M-C(3) _O(3),3.0,48.0
3,Entity-Destination,C-C(5) _O(2),2.0,78.0
4,Entity-Origin,C-E(1) C-W(1) M-T(1) P-P(5) _O(3),3.0,61.0
5,Instrument-Agency,C-W(1) E-O(1) P-P(3) _O(5),5.0,41.0
6,Member-Collection,C-W(1) E-O(1) M-T(2) _O(3),3.0,62.0
7,Message-Topic,C-E(1) C-W(1) E-D(2) _O(3),3.0,56.0
8,Product-Producer,C-E(2) E-D(3) E-O(5) I-A(2) M-C(1) M-T(1) _O(7),7.0,51.0
9,Other,C-E(5) C-W(16) C-C(3) E-D(11) E-O(15) I-A(15) ...,NaN,43.0

# Fold2

In [50]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold2', 'error-analysis/piecewise-pool/Fold2', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic 1.24 	 p_value 0.24875146569640855
Metric: Recall 	 statistic -0.25 	 p_value 0.8106306202357357
Metric: F1 	 statistic 1.01 	 p_value 0.3410477012807563

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic 0.40 	 p_value 0.7019053739630096
Metric: Recall 	 statistic 0.02 	 p_value 0.9858975973046158
Metric: F1 	 statistic 1.11 	 p_value 0.29404482867833526

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro 0.03
Metric: Recall 	 Macro-Micro -0.21
Metric: F1 	 Macro-Micro -0.21

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro 0.36
Metric: Recall 	 Macro-Micro -0.22
Metric: F1 	 Macro-Micro -0.22

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference 1.19
Metric: Recall 	 Difference -0.29
Metric: F1 	 Difference 0.70

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference 1.52
Metric: Recall 	 Difference -0.30
Metric: F1 	 Difference 0.69
Accuracy_Baseline - Accuracy_Piecewise-Pool 0.24

In [51]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(2) M-T(2) _O(5),5.0,90.0
1,Component-Whole,C-E(2) C-C(3) E-O(2) I-A(4) M-C(3) M-T(6) _O(5),5.0,65.0
2,Content-Container,C-W(3) E-D(1) M-C(1) _O(2),2.0,48.0
3,Entity-Destination,C-C(2) _O(4),4.0,79.0
4,Entity-Origin,C-E(3) C-W(1) M-T(1) P-P(2) _O(5),5.0,60.0
5,Instrument-Agency,C-W(4) P-P(2) _O(9),9.0,36.0
6,Member-Collection,C-W(2) _O(5),5.0,62.0
7,Message-Topic,C-E(1) C-W(1) P-P(1) _O(3),3.0,56.0
8,Product-Producer,C-E(2) C-W(1) E-D(1) E-O(4) I-A(3) _O(7),7.0,53.0
9,Other,C-E(8) C-W(16) C-C(4) E-D(12) E-O(16) I-A(5) M...,NaN,46.0

In [52]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(3) C-C(1) E-O(3) M-T(2) _O(2),2.0,89.0
1,Component-Whole,C-E(1) C-C(2) E-O(1) I-A(2) M-C(5) M-T(7) _O(6),6.0,68.0
2,Content-Container,C-W(2) M-C(1) _O(2),2.0,50.0
3,Entity-Destination,C-C(2) _O(3),3.0,80.0
4,Entity-Origin,C-E(4) C-W(1) M-T(1) P-P(3) _O(4),4.0,59.0
5,Instrument-Agency,C-E(2) C-W(5) M-C(1) M-T(2) P-P(2) _O(4),4.0,35.0
6,Member-Collection,C-W(1) _O(3),3.0,65.0
7,Message-Topic,C-E(2) P-P(1) _O(3),3.0,57.0
8,Product-Producer,C-E(4) C-W(3) E-D(1) E-O(6) I-A(3) M-T(1) _O(5),5.0,48.0
9,Other,C-E(9) C-W(17) C-C(7) E-D(13) E-O(15) I-A(4) M...,NaN,42.0

# Fold3

In [53]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold3', 'error-analysis/piecewise-pool/Fold3', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic 0.08 	 p_value 0.9351839343831326
Metric: Recall 	 statistic 0.75 	 p_value 0.47375187998545387
Metric: F1 	 statistic 0.74 	 p_value 0.4783796467274599

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic -0.29 	 p_value 0.7752756183362655
Metric: Recall 	 statistic 0.38 	 p_value 0.7113680183315421
Metric: F1 	 statistic 0.08 	 p_value 0.9359298414868621

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.21
Metric: Recall 	 Macro-Micro 0.04
Metric: F1 	 Macro-Micro -0.21

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro -0.11
Metric: Recall 	 Macro-Micro -0.10
Metric: F1 	 Macro-Micro -0.26

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference 0.10
Metric: Recall 	 Difference 1.05
Metric: F1 	 Difference 0.57

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference 0.20
Metric: Recall 	 Difference 0.91
Metric: F1 	 Difference 0.52
Accuracy_Baseline - Accuracy_Piecewise-Pool 0.00

In [54]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(4) M-T(1) P-P(1) _O(6),6.0,85.0
1,Component-Whole,C-C(5) E-O(1) I-A(5) M-T(2) P-P(1) _O(12),12.0,68.0
2,Content-Container,C-W(3) E-D(3) _O(3),3.0,45.0
3,Entity-Destination,C-C(2) M-T(1) _O(2),2.0,79.0
4,Entity-Origin,C-E(6) M-C(1) _O(1),1.0,64.0
5,Instrument-Agency,C-W(1) E-O(1) M-T(1) _O(6),6.0,42.0
6,Member-Collection,P-P(1) _O(5),5.0,63.0
7,Message-Topic,C-W(4) E-D(1) E-O(1) P-P(2) _O(6),6.0,49.0
8,Product-Producer,C-E(2) C-W(1) E-D(2) E-O(1) I-A(2) _O(6),6.0,57.0
9,Other,C-E(10) C-W(15) C-C(5) E-D(11) E-O(18) I-A(13)...,NaN,35.0

In [55]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(2) E-O(5) M-T(1) _O(5),5.0,85.0
1,Component-Whole,C-C(6) I-A(2) M-T(4) _O(12),12.0,70.0
2,Content-Container,C-W(3) E-D(2) M-T(1) _O(3),3.0,45.0
3,Entity-Destination,C-W(1) C-C(2) M-T(1),0.0,80.0
4,Entity-Origin,C-E(7) M-C(1) M-T(1) _O(3),3.0,60.0
5,Instrument-Agency,C-W(1) E-O(1) M-T(1) P-P(1) _O(5),5.0,41.0
6,Member-Collection,P-P(1) _O(4),4.0,64.0
7,Message-Topic,C-W(5) E-O(1) _O(6),6.0,51.0
8,Product-Producer,C-E(2) C-W(1) E-D(3) E-O(1) I-A(3) M-T(2) _O(9),9.0,50.0
9,Other,C-E(10) C-W(12) C-C(4) E-D(13) E-O(12) I-A(10)...,NaN,41.0

# Fold4

In [56]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold4', 'error-analysis/piecewise-pool/Fold4', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic 0.83 	 p_value 0.43327875044338016
Metric: Recall 	 statistic 0.28 	 p_value 0.7874804546528433
Metric: F1 	 statistic 0.57 	 p_value 0.5811434378392968

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic 1.07 	 p_value 0.31337862498281344
Metric: Recall 	 statistic 0.53 	 p_value 0.6058050544282914
Metric: F1 	 statistic 0.91 	 p_value 0.3863326581411086

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.20
Metric: Recall 	 Macro-Micro 0.00
Metric: F1 	 Macro-Micro -0.23

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro -0.06
Metric: Recall 	 Macro-Micro -0.11
Metric: F1 	 Macro-Micro -0.15

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference 0.80
Metric: Recall 	 Difference 0.41
Metric: F1 	 Difference 0.57

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference 0.94
Metric: Recall 	 Difference 0.30
Metric: F1 	 Difference 0.65
Accuracy_Baseline - Accuracy_Piecewise-Pool 0.87

In [57]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(2) _O(9),9.0,89.0
1,Component-Whole,C-C(1) E-O(1) I-A(3) M-C(1) M-T(5) _O(8),8.0,72.0
2,Content-Container,C-W(1) _O(2),2.0,51.0
3,Entity-Destination,C-C(3) E-O(1) _O(2),2.0,78.0
4,Entity-Origin,C-E(2) M-T(1) P-P(2) _O(2),2.0,65.0
5,Instrument-Agency,C-W(2) E-D(2) M-T(1) P-P(2) _O(4),4.0,40.0
6,Member-Collection,C-W(4) C-C(1) E-D(1) _O(6),6.0,57.0
7,Message-Topic,C-E(1) C-W(3) _O(4),4.0,54.0
8,Product-Producer,C-E(1) C-W(3) E-D(2) E-O(4) I-A(3) _O(6),6.0,52.0
9,Other,C-E(11) C-W(12) C-C(9) E-D(13) E-O(10) I-A(9) ...,NaN,48.0

In [58]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(1) P-P(1) _O(9),9.0,87.0
1,Component-Whole,C-E(1) C-C(1) E-O(1) I-A(3) M-C(1) M-T(4) P-P(...,9.0,70.0
2,Content-Container,C-W(3) E-D(1) _O(3),3.0,47.0
3,Entity-Destination,C-C(3) E-O(1) _O(1),1.0,79.0
4,Entity-Origin,C-E(2) P-P(2),0.0,68.0
5,Instrument-Agency,C-W(2) E-D(2) E-O(2) P-P(2) _O(3),3.0,40.0
6,Member-Collection,C-W(1) E-D(1) P-P(1) _O(4),4.0,62.0
7,Message-Topic,C-E(2) C-W(3) _O(5),5.0,51.0
8,Product-Producer,C-E(1) C-W(1) C-C(1) E-D(2) E-O(2) I-A(4) _O(8),8.0,52.0
9,Other,C-E(13) C-W(14) C-C(8) E-D(13) E-O(11) I-A(5) ...,NaN,43.0

# Fold5

In [59]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold5', 'error-analysis/piecewise-pool/Fold5', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -0.98 	 p_value 0.3558856495481102
Metric: Recall 	 statistic -0.29 	 p_value 0.7815515769792953
Metric: F1 	 statistic -1.22 	 p_value 0.25737094372857666

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic -0.75 	 p_value 0.4717780959469837
Metric: Recall 	 statistic -0.68 	 p_value 0.5143280298106065
Metric: F1 	 statistic -1.63 	 p_value 0.13717016113141045

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro 0.17
Metric: Recall 	 Macro-Micro -0.59
Metric: F1 	 Macro-Micro -0.26

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro -0.26
Metric: Recall 	 Macro-Micro -0.33
Metric: F1 	 Macro-Micro -0.36

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference -0.86
Metric: Recall 	 Difference -0.26
Metric: F1 	 Difference -0.60

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference -1.29
Metric: Recall 	 Difference 0.00
Metric: F1 	 Difference -0.70
Accuracy_Baseline - Accuracy_Piecewise-Pool -0.62

In [60]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(4) E-O(2) P-P(1) _O(5),5.0,87.0
1,Component-Whole,C-C(3) E-D(1) E-O(1) M-C(1) M-T(3) _O(9),9.0,72.0
2,Content-Container,C-W(5) E-D(3) I-A(1) _O(1),1.0,43.0
3,Entity-Destination,C-C(3) _O(1),1.0,81.0
4,Entity-Origin,C-E(6) C-W(3) I-A(2) _O(2),2.0,59.0
5,Instrument-Agency,C-W(5) C-C(1) E-O(1) P-P(3) _O(5),5.0,36.0
6,Member-Collection,C-W(4) M-T(1) P-P(1) _O(4),4.0,59.0
7,Message-Topic,C-W(1) E-D(2) I-A(1) _O(4),4.0,55.0
8,Product-Producer,C-E(1) C-W(2) C-C(1) E-D(1) E-O(3) I-A(1) _O(6),6.0,56.0
9,Other,C-E(13) C-W(11) C-C(7) E-D(14) E-O(7) I-A(8) M...,NaN,43.0

In [61]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(1) P-P(1) _O(7),7.0,88.0
1,Component-Whole,C-C(3) E-D(1) I-A(1) M-C(1) M-T(3) P-P(1) _O(11),11.0,69.0
2,Content-Container,C-W(5) E-D(3) I-A(1) _O(1),1.0,42.0
3,Entity-Destination,C-C(4) _O(1),1.0,80.0
4,Entity-Origin,C-E(4) C-W(2) I-A(2) M-T(1) P-P(1) _O(4),4.0,58.0
5,Instrument-Agency,C-W(4) E-O(1) M-T(1) P-P(2) _O(4),4.0,39.0
6,Member-Collection,C-W(2) C-C(1) P-P(2) _O(4),4.0,60.0
7,Message-Topic,C-W(1) E-D(1) P-P(1) _O(4),4.0,56.0
8,Product-Producer,C-E(1) E-D(1) E-O(3) I-A(2) _O(8),8.0,56.0
9,Other,C-E(9) C-W(13) C-C(7) E-D(13) E-O(7) I-A(10) M...,NaN,48.0

# Fold6

In [62]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold6', 'error-analysis/piecewise-pool/Fold6', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -1.07 	 p_value 0.3162231214711385
Metric: Recall 	 statistic 0.02 	 p_value 0.9811040435781746
Metric: F1 	 statistic -0.47 	 p_value 0.6538409718927575

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic -0.29 	 p_value 0.7805411292795922
Metric: Recall 	 statistic 0.12 	 p_value 0.9063228996946217
Metric: F1 	 statistic -0.08 	 p_value 0.9373875216073168

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.70
Metric: Recall 	 Macro-Micro -0.29
Metric: F1 	 Macro-Micro -0.67

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro -0.74
Metric: Recall 	 Macro-Micro -0.64
Metric: F1 	 Macro-Micro -1.01

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference -1.14
Metric: Recall 	 Difference 0.04
Metric: F1 	 Difference -0.44

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference -1.18
Metric: Recall 	 Difference -0.31
Metric: F1 	 Difference -0.78
Accuracy_Baseline - Accuracy_Piecewise-Pool 0.00

In [63]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(2) M-T(2) _O(3),3.0,90.0
1,Component-Whole,C-C(4) E-D(1) E-O(1) I-A(5) M-C(2) _O(9),9.0,70.0
2,Content-Container,C-W(1) M-C(1) _O(3),3.0,48.0
3,Entity-Destination,C-C(5) _O(1),1.0,78.0
4,Entity-Origin,C-E(1) M-T(1) P-P(1) _O(2),2.0,66.0
5,Instrument-Agency,C-W(6) E-O(1) P-P(1) _O(5),5.0,36.0
6,Member-Collection,C-W(2) _O(5),5.0,62.0
7,Message-Topic,C-W(2) E-D(1) E-O(1) _O(4),4.0,52.0
8,Product-Producer,C-E(1) C-W(4) E-D(1) E-O(3) I-A(6) M-C(1) _O(6),6.0,49.0
9,Other,C-E(9) C-W(12) C-C(9) E-D(8) E-O(11) I-A(7) M-...,NaN,54.0

In [64]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(1) M-T(3) _O(3),3.0,91.0
1,Component-Whole,C-C(3) E-O(1) I-A(2) M-C(2) P-P(1) _O(12),12.0,72.0
2,Content-Container,C-W(1) E-D(1) _O(1),1.0,50.0
3,Entity-Destination,C-C(4) _O(1),1.0,79.0
4,Entity-Origin,C-E(1) M-T(1) _O(3),3.0,66.0
5,Instrument-Agency,C-W(8) E-O(1) P-P(1) _O(8),8.0,31.0
6,Member-Collection,C-W(1) _O(2),2.0,66.0
7,Message-Topic,C-W(2) E-D(1) E-O(1) _O(4),4.0,53.0
8,Product-Producer,C-E(1) E-D(1) E-O(4) I-A(5) M-C(1) _O(14),14.0,45.0
9,Other,C-E(11) C-W(11) C-C(6) E-D(8) E-O(11) I-A(6) M...,NaN,52.0

# Fold7

In [65]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold7', 'error-analysis/piecewise-pool/Fold7', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -2.57 	 p_value 0.033353170812238764
Metric: Recall 	 statistic -0.06 	 p_value 0.9525360743136506
Metric: F1 	 statistic -1.34 	 p_value 0.21586149564218549

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic -2.24 	 p_value 0.05202776542070175
Metric: Recall 	 statistic -0.54 	 p_value 0.600500694444232
Metric: F1 	 statistic -1.80 	 p_value 0.10464631225291239

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.25
Metric: Recall 	 Macro-Micro -0.04
Metric: F1 	 Macro-Micro -0.29

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro -0.67
Metric: Recall 	 Macro-Micro 0.24
Metric: F1 	 Macro-Micro -0.41

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference -2.39
Metric: Recall 	 Difference -0.12
Metric: F1 	 Difference -1.31

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference -2.81
Metric: Recall 	 Difference 0.16
Metric: F1 	 Difference -1.43
Accuracy_Baseline - Accuracy_Piecewise-Pool -1.64

In [66]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(1) M-T(3) P-P(1) _O(8),8.0,87.0
1,Component-Whole,C-C(5) E-O(2) I-A(3) M-T(2) P-P(1) _O(1),1.0,79.0
2,Content-Container,C-W(2) E-D(1),0.0,50.0
3,Entity-Destination,C-W(1) C-C(4) E-O(1) M-T(3),0.0,75.0
4,Entity-Origin,C-E(1) C-W(2) C-C(1) E-D(1) I-A(1) M-T(1) _O(6),6.0,57.0
5,Instrument-Agency,C-W(3) E-D(1) P-P(2) _O(1),1.0,41.0
6,Member-Collection,C-E(1) C-W(2) C-C(1) M-T(1) _O(2),2.0,61.0
7,Message-Topic,C-W(4) _O(10),10.0,47.0
8,Product-Producer,C-W(1) E-O(3) I-A(1) M-T(2) _O(5),5.0,59.0
9,Other,C-E(6) C-W(18) C-C(6) E-D(7) E-O(13) I-A(7) M-...,NaN,47.0

In [67]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(1) M-T(1) _O(7),7.0,91.0
1,Component-Whole,C-C(5) E-O(1) I-A(4) M-T(3) P-P(1) _O(7),7.0,73.0
2,Content-Container,C-W(2) E-D(1),0.0,49.0
3,Entity-Destination,C-W(1) C-C(4) M-T(2) _O(3),3.0,74.0
4,Entity-Origin,C-E(2) C-W(1) C-C(1) E-D(1) M-T(1) _O(5),5.0,59.0
5,Instrument-Agency,C-W(1) P-P(2) _O(3),3.0,43.0
6,Member-Collection,C-C(1) P-P(1) _O(3),3.0,63.0
7,Message-Topic,C-W(1) E-O(1) _O(6),6.0,52.0
8,Product-Producer,C-W(2) E-O(3) I-A(2) M-C(1) M-T(1) _O(11),11.0,51.0
9,Other,C-E(6) C-W(13) C-C(6) E-D(5) E-O(11) I-A(6) M-...,NaN,61.0

# Fold8

In [68]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold8', 'error-analysis/piecewise-pool/Fold8', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic 0.56 	 p_value 0.5905362172538382
Metric: Recall 	 statistic 0.20 	 p_value 0.8479838439363054
Metric: F1 	 statistic 0.49 	 p_value 0.6373705462770953

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic 0.70 	 p_value 0.5002826383195611
Metric: Recall 	 statistic 0.57 	 p_value 0.5814215560455976
Metric: F1 	 statistic 0.81 	 p_value 0.43706021492621494

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.51
Metric: Recall 	 Macro-Micro 0.22
Metric: F1 	 Macro-Micro -0.40

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro -0.60
Metric: Recall 	 Macro-Micro 0.12
Metric: F1 	 Macro-Micro -0.46

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference 1.19
Metric: Recall 	 Difference 0.26
Metric: F1 	 Difference 0.74

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference 1.10
Metric: Recall 	 Difference 0.16
Metric: F1 	 Difference 0.68
Accuracy_Baseline - Accuracy_Piecewise-Pool 1.01

In [69]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(2) E-O(5) P-P(3) _O(6),6.0,82.0
1,Component-Whole,C-E(1) C-C(2) E-D(1) I-A(5) M-C(4) M-T(3) _O(4),4.0,72.0
2,Content-Container,C-W(1) E-D(2) _O(3),3.0,47.0
3,Entity-Destination,C-C(1) E-O(1) P-P(1),0.0,81.0
4,Entity-Origin,C-E(1) C-C(1) E-D(1) M-C(1) P-P(2) _O(1),1.0,62.0
5,Instrument-Agency,C-W(2) M-T(2) P-P(1) _O(2),2.0,41.0
6,Member-Collection,E-O(1) P-P(1) _O(2),2.0,64.0
7,Message-Topic,C-W(3) I-A(1) _O(6),6.0,52.0
8,Product-Producer,C-W(1) E-D(3) E-O(4) I-A(2) M-C(1) M-T(1) _O(12),12.0,47.0
9,Other,C-E(9) C-W(12) C-C(6) E-D(10) E-O(13) I-A(13) ...,NaN,46.0

In [70]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(2) E-D(1) E-O(4) M-T(1) P-P(3) _O(4),4.0,82.0
1,Component-Whole,C-E(1) C-C(4) E-D(1) I-A(3) M-C(4) M-T(3) _O(4),4.0,72.0
2,Content-Container,C-W(1) E-D(1) _O(2),2.0,49.0
3,Entity-Destination,C-C(2) E-O(1) P-P(1),0.0,80.0
4,Entity-Origin,C-E(2) C-C(1) M-C(1) M-T(1) _O(1),1.0,63.0
5,Instrument-Agency,C-W(3) C-C(1) M-T(1) P-P(2) _O(3),3.0,39.0
6,Member-Collection,C-W(1) E-O(1) _O(2),2.0,64.0
7,Message-Topic,E-D(1) _O(9),9.0,47.0
8,Product-Producer,E-D(1) E-O(6) I-A(1) M-C(1) M-T(1) _O(9),9.0,51.0
9,Other,C-E(9) C-W(13) C-C(9) E-D(9) E-O(13) I-A(11) M...,NaN,39.0

# Fold9

In [71]:
summary_cm_baseline, summary_cm_piecewise = print_full_summary(
    'error-analysis/baseline/Fold9', 'error-analysis/piecewise-pool/Fold9', 
    'Baseline','Piecewise-Pool', res, relation_full_form_dictionary, relation_as_short_list, 2)

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic 0.79 	 p_value 0.45503526971118247
Metric: Recall 	 statistic 0.40 	 p_value 0.7004032103941142
Metric: F1 	 statistic 0.83 	 p_value 0.42942162036056675

TTest from Baseline to Piecewise-Pool
Below is the metric comparsion across the two models considering individual relations, including 'Other'
Metric: Precision 	 statistic 0.63 	 p_value 0.5443624363273211
Metric: Recall 	 statistic 0.50 	 p_value 0.6301355004860415
Metric: F1 	 statistic 1.00 	 p_value 0.34336296537388805

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.22
Metric: Recall 	 Macro-Micro 0.23
Metric: F1 	 Macro-Micro -0.12

Macro - Micro for the Piecewise-Pool model
Metric: Precision 	 Macro-Micro -0.26
Metric: Recall 	 Macro-Micro -0.26
Metric: F1 	 Macro-Micro -0.36

Macro_Baseline - Macro_Piecewise-Pool
Metric: Precision 	 Difference 0.59
Metric: Recall 	 Difference 0.64
Metric: F1 	 Difference 0.61

Micro_Baseline - Micro_Piecewise-Pool
Metric: Precision 	 Difference 0.55
Metric: Recall 	 Difference 0.15
Metric: F1 	 Difference 0.37
Accuracy_Baseline - Accuracy_Piecewise-Pool 0.37

In [72]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(5) P-P(2) _O(2),2.0,90.0
1,Component-Whole,C-C(4) E-D(1) E-O(4) I-A(4) M-C(1) M-T(3) P-P(...,4.0,70.0
2,Content-Container,C-W(1) E-D(3) _O(2),2.0,47.0
3,Entity-Destination,C-W(1) C-C(1) M-T(1) _O(1),1.0,81.0
4,Entity-Origin,C-E(4) C-W(1) I-A(1) M-T(1) P-P(3) _O(5),5.0,57.0
5,Instrument-Agency,C-W(1) E-O(1) P-P(1) _O(2),2.0,46.0
6,Member-Collection,C-W(1) C-C(1) E-O(1) P-P(3) _O(2),2.0,60.0
7,Message-Topic,C-E(1) C-W(1) E-O(1) _O(4),4.0,56.0
8,Product-Producer,C-W(3) C-C(1) E-O(3) M-C(1) M-T(1) _O(2),2.0,62.0
9,Other,C-E(6) C-W(14) C-C(5) E-D(10) E-O(13) I-A(11) ...,NaN,46.0

In [73]:
summary_cm_piecewise

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(5) P-P(2) _O(1),1.0,90.0
1,Component-Whole,C-E(1) C-C(4) E-O(4) I-A(3) M-C(1) M-T(4) P-P(...,3.0,71.0
2,Content-Container,E-D(3) _O(3),3.0,47.0
3,Entity-Destination,C-W(1) C-C(1) M-C(1),0.0,82.0
4,Entity-Origin,C-E(3) C-W(1) E-D(1) I-A(1) M-T(1) P-P(3) _O(3),3.0,59.0
5,Instrument-Agency,C-W(2) E-O(1) M-C(1) P-P(2) _O(5),5.0,40.0
6,Member-Collection,C-C(1) M-T(1) P-P(2) _O(2),2.0,63.0
7,Message-Topic,C-E(1) C-W(2) E-D(2) E-O(1) P-P(1) _O(2),2.0,53.0
8,Product-Producer,C-W(3) E-O(3) M-C(1) _O(3),3.0,63.0
9,Other,C-E(7) C-W(13) C-C(8) E-D(11) E-O(11) I-A(8) M...,NaN,44.0