# Fold Level Error analysis between Elmo vs Baseline

In [2]:
%load_ext autoreload

In [4]:
%autoreload
import os
from sys import path
import re
import pandas as pd
path.append('../..')
import numpy as np
from scipy.stats import ttest_rel
from relation_extraction.data.summarize_semeval2010 import *
output_path = '/scratch/geeticka/relation-extraction/output/semeval2010/CrossValidation'
def res(path): return os.path.join(output_path, path)

relation_full_form_dictionary = {'C-E': 'Cause-Effect', 'C-W': 'Component-Whole', 'C-C': 'Content-Container',
                                 'E-D': 'Entity-Destination', 'E-O': 'Entity-Origin', 'I-A': 'Instrument-Agency',
                                 'M-C': 'Member-Collection', 'M-T': 'Message-Topic', 'P-P': 'Product-Producer',
                                 '_O': 'Other'}
relation_as_short_list = ['C-E', 'C-W', 'C-C', 'E-D', 'E-O', 'I-A', 'M-C', 'M-T', 'P-P', '_O']

# Fold0

In [5]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold0', 'error-analysis/elmo-model/Fold0', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -5.38 	 p_value 0.0006647655060868683
Metric: Recall 	 statistic 0.45 	 p_value 0.6644537071409055
Metric: F1 	 statistic -3.34 	 p_value 0.010214137647466863

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro 0.37
Metric: Recall 	 Macro-Micro -0.77
Metric: F1 	 Macro-Micro -0.47

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro 0.71
Metric: Recall 	 Macro-Micro -1.07
Metric: F1 	 Macro-Micro -0.64

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -7.46
Metric: Recall 	 Difference 0.75
Metric: F1 	 Difference -3.21

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -7.12
Metric: Recall 	 Difference 0.45
Metric: F1 	 Difference -3.38
Accuracy_Baseline - Accuracy_Elmo -3.23

In [6]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(6) M-T(1) P-P(1) _O(2),2.0,91.0
1,Component-Whole,C-C(1) E-O(2) M-C(1) M-T(2) _O(12),12.0,71.0
2,Content-Container,C-W(2) E-D(4) _O(1),1.0,48.0
3,Entity-Destination,C-C(1),0.0,84.0
4,Entity-Origin,C-W(1) _O(4),4.0,67.0
5,Instrument-Agency,C-W(5) E-O(1) M-T(2) P-P(2) _O(6),6.0,34.0
6,Member-Collection,C-W(2) C-C(2) _O(2),2.0,64.0
7,Message-Topic,C-W(1) E-D(1) P-P(2) _O(8),8.0,50.0
8,Product-Producer,C-E(1) E-D(1) E-O(3) I-A(1) M-C(1) _O(9),9.0,57.0
9,Other,C-E(10) C-W(15) C-C(4) E-D(11) E-O(9) I-A(4) M...,NaN,56.0

In [7]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(3) P-P(1) _O(2),2.0,95.0
1,Component-Whole,M-C(2) M-T(2) _O(21),21.0,68.0
2,Content-Container,E-D(6) _O(6),6.0,43.0
3,Entity-Destination,_O(2),2.0,83.0
4,Entity-Origin,C-W(1) _O(6),6.0,65.0
5,Instrument-Agency,C-W(3) M-T(1) _O(12),12.0,34.0
6,Member-Collection,C-W(2) _O(7),7.0,61.0
7,Message-Topic,_O(13),13.0,51.0
8,Product-Producer,E-O(3) _O(7),7.0,63.0
9,Other,C-E(8) C-W(8) C-C(1) E-D(7) E-O(8) I-A(1) M-C(...,NaN,85.0

# Fold1

In [8]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold1', 'error-analysis/elmo-model/Fold1', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -7.59 	 p_value 6.385268618285926e-05
Metric: Recall 	 statistic -1.58 	 p_value 0.15349204754464224
Metric: F1 	 statistic -5.29 	 p_value 0.0007348387224285373

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.64
Metric: Recall 	 Macro-Micro -0.16
Metric: F1 	 Macro-Micro -0.51

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro -0.13
Metric: Recall 	 Macro-Micro 0.18
Metric: F1 	 Macro-Micro -0.12

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -8.61
Metric: Recall 	 Difference -1.85
Metric: F1 	 Difference -5.27

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -8.10
Metric: Recall 	 Difference -1.51
Metric: F1 	 Difference -4.88
Accuracy_Baseline - Accuracy_Elmo -6.46

In [9]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(2) I-A(1) P-P(2) _O(5),5.0,90.0
1,Component-Whole,C-C(2) I-A(2) M-C(2) M-T(3) P-P(1) _O(13),13.0,69.0
2,Content-Container,E-D(1) M-C(2) _O(1),1.0,51.0
3,Entity-Destination,C-C(7) _O(3),3.0,75.0
4,Entity-Origin,C-E(1) C-W(1) I-A(1) P-P(2) _O(3),3.0,64.0
5,Instrument-Agency,C-W(2) P-P(3) _O(10),10.0,36.0
6,Member-Collection,C-W(2) C-C(1) E-O(1) M-T(1) _O(5),5.0,58.0
7,Message-Topic,C-E(1) C-W(1) E-D(2) _O(6),6.0,54.0
8,Product-Producer,C-E(1) C-C(1) E-D(1) E-O(6) I-A(2) _O(8),8.0,53.0
9,Other,C-E(10) C-W(14) C-C(4) E-D(10) E-O(14) I-A(13)...,NaN,44.0

In [10]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(1) I-A(1) P-P(2) _O(11),11.0,86.0
1,Component-Whole,C-C(1) I-A(1) M-C(1) M-T(3) P-P(1) _O(15),15.0,70.0
2,Content-Container,E-D(1) M-C(1) _O(3),3.0,50.0
3,Entity-Destination,C-C(5) E-O(1) _O(3),3.0,76.0
4,Entity-Origin,C-E(1) P-P(2) _O(4),4.0,65.0
5,Instrument-Agency,C-W(2) _O(10),10.0,39.0
6,Member-Collection,C-W(1) E-O(1) _O(4),4.0,63.0
7,Message-Topic,E-D(1) _O(8),8.0,55.0
8,Product-Producer,C-E(1) E-O(4) I-A(2) _O(9),9.0,56.0
9,Other,C-E(4) C-W(8) C-C(2) E-D(3) E-O(14) I-A(6) M-C...,NaN,86.0

# Fold2

In [11]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold2', 'error-analysis/elmo-model/Fold2', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -4.70 	 p_value 0.0015320161713513448
Metric: Recall 	 statistic 0.27 	 p_value 0.7970285191825257
Metric: F1 	 statistic -4.39 	 p_value 0.0023094858367941947

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro 0.03
Metric: Recall 	 Macro-Micro -0.21
Metric: F1 	 Macro-Micro -0.21

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro 0.15
Metric: Recall 	 Macro-Micro -0.03
Metric: F1 	 Macro-Micro -0.25

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -6.99
Metric: Recall 	 Difference 0.28
Metric: F1 	 Difference -3.27

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -6.87
Metric: Recall 	 Difference 0.46
Metric: F1 	 Difference -3.31
Accuracy_Baseline - Accuracy_Elmo -2.87

In [12]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(2) M-T(2) _O(5),5.0,90.0
1,Component-Whole,C-E(2) C-C(3) E-O(2) I-A(4) M-C(3) M-T(6) _O(5),5.0,65.0
2,Content-Container,C-W(3) E-D(1) M-C(1) _O(2),2.0,48.0
3,Entity-Destination,C-C(2) _O(4),4.0,79.0
4,Entity-Origin,C-E(3) C-W(1) M-T(1) P-P(2) _O(5),5.0,60.0
5,Instrument-Agency,C-W(4) P-P(2) _O(9),9.0,36.0
6,Member-Collection,C-W(2) _O(5),5.0,62.0
7,Message-Topic,C-E(1) C-W(1) P-P(1) _O(3),3.0,56.0
8,Product-Producer,C-E(2) C-W(1) E-D(1) E-O(4) I-A(3) _O(7),7.0,53.0
9,Other,C-E(8) C-W(16) C-C(4) E-D(12) E-O(16) I-A(5) M...,NaN,46.0

In [13]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(2) M-T(1) _O(11),11.0,85.0
1,Component-Whole,C-E(1) C-C(1) I-A(1) M-C(3) M-T(4) _O(21),21.0,62.0
2,Content-Container,C-W(1) M-C(1) _O(5),5.0,48.0
3,Entity-Destination,C-C(2) _O(3),3.0,80.0
4,Entity-Origin,C-E(3) C-W(2) _O(5),5.0,62.0
5,Instrument-Agency,P-P(2) _O(15),15.0,34.0
6,Member-Collection,C-W(1) P-P(1) _O(4),4.0,63.0
7,Message-Topic,E-D(1) P-P(1) _O(6),6.0,56.0
8,Product-Producer,C-E(1) E-O(3) I-A(1) _O(11),11.0,56.0
9,Other,C-E(7) C-W(8) C-C(1) E-D(9) E-O(13) I-A(4) M-C...,NaN,72.0

# Fold3

In [14]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold3', 'error-analysis/elmo-model/Fold3', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -4.49 	 p_value 0.002030225248924379
Metric: Recall 	 statistic -0.06 	 p_value 0.951619977993911
Metric: F1 	 statistic -3.30 	 p_value 0.010846231222625785

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.21
Metric: Recall 	 Macro-Micro 0.04
Metric: F1 	 Macro-Micro -0.21

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro 0.02
Metric: Recall 	 Macro-Micro -0.17
Metric: F1 	 Macro-Micro -0.15

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -5.93
Metric: Recall 	 Difference -0.09
Metric: F1 	 Difference -3.20

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -5.70
Metric: Recall 	 Difference -0.30
Metric: F1 	 Difference -3.14
Accuracy_Baseline - Accuracy_Elmo -4.00

In [15]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(4) M-T(1) P-P(1) _O(6),6.0,85.0
1,Component-Whole,C-C(5) E-O(1) I-A(5) M-T(2) P-P(1) _O(12),12.0,68.0
2,Content-Container,C-W(3) E-D(3) _O(3),3.0,45.0
3,Entity-Destination,C-C(2) M-T(1) _O(2),2.0,79.0
4,Entity-Origin,C-E(6) M-C(1) _O(1),1.0,64.0
5,Instrument-Agency,C-W(1) E-O(1) M-T(1) _O(6),6.0,42.0
6,Member-Collection,P-P(1) _O(5),5.0,63.0
7,Message-Topic,C-W(4) E-D(1) E-O(1) P-P(2) _O(6),6.0,49.0
8,Product-Producer,C-E(2) C-W(1) E-D(2) E-O(1) I-A(2) _O(6),6.0,57.0
9,Other,C-E(10) C-W(15) C-C(5) E-D(11) E-O(18) I-A(13)...,NaN,35.0

In [16]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(4) M-T(1) _O(7),7.0,85.0
1,Component-Whole,C-C(3) I-A(3) M-C(1) M-T(2) _O(14),14.0,70.0
2,Content-Container,C-W(3) E-D(3) _O(6),6.0,42.0
3,Entity-Destination,C-W(1) C-C(1) _O(1),1.0,81.0
4,Entity-Origin,C-E(3) I-A(1) _O(9),9.0,59.0
5,Instrument-Agency,P-P(1) _O(9),9.0,41.0
6,Member-Collection,_O(5),5.0,64.0
7,Message-Topic,C-W(2) E-O(1) _O(6),6.0,54.0
8,Product-Producer,C-E(1) C-W(2) E-D(1) E-O(1) I-A(1) _O(7),7.0,58.0
9,Other,C-E(9) C-W(11) C-C(4) E-D(12) E-O(9) I-A(5) M-...,NaN,65.0

# Fold4

In [17]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold4', 'error-analysis/elmo-model/Fold4', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -4.33 	 p_value 0.002505136868953965
Metric: Recall 	 statistic 0.37 	 p_value 0.7179393286062645
Metric: F1 	 statistic -3.39 	 p_value 0.00953152378562655

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.20
Metric: Recall 	 Macro-Micro 0.00
Metric: F1 	 Macro-Micro -0.23

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro -0.16
Metric: Recall 	 Macro-Micro -0.04
Metric: F1 	 Macro-Micro -0.20

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -4.66
Metric: Recall 	 Difference 0.65
Metric: F1 	 Difference -2.14

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -4.62
Metric: Recall 	 Difference 0.61
Metric: F1 	 Difference -2.11
Accuracy_Baseline - Accuracy_Elmo -1.63

In [18]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(2) _O(9),9.0,89.0
1,Component-Whole,C-C(1) E-O(1) I-A(3) M-C(1) M-T(5) _O(8),8.0,72.0
2,Content-Container,C-W(1) _O(2),2.0,51.0
3,Entity-Destination,C-C(3) E-O(1) _O(2),2.0,78.0
4,Entity-Origin,C-E(2) M-T(1) P-P(2) _O(2),2.0,65.0
5,Instrument-Agency,C-W(2) E-D(2) M-T(1) P-P(2) _O(4),4.0,40.0
6,Member-Collection,C-W(4) C-C(1) E-D(1) _O(6),6.0,57.0
7,Message-Topic,C-E(1) C-W(3) _O(4),4.0,54.0
8,Product-Producer,C-E(1) C-W(3) E-D(2) E-O(4) I-A(3) _O(6),6.0,52.0
9,Other,C-E(11) C-W(12) C-C(9) E-D(13) E-O(10) I-A(9) ...,NaN,48.0

In [19]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(1) _O(11),11.0,88.0
1,Component-Whole,C-C(1) E-O(1) I-A(4) M-C(1) M-T(2) _O(16),16.0,67.0
2,Content-Container,E-D(1) _O(8),8.0,45.0
3,Entity-Destination,C-C(2) _O(2),2.0,80.0
4,Entity-Origin,C-E(1) P-P(1) _O(6),6.0,64.0
5,Instrument-Agency,C-W(1) E-D(1) P-P(2) _O(6),6.0,41.0
6,Member-Collection,C-W(2) E-D(1) _O(4),4.0,62.0
7,Message-Topic,C-W(1) _O(8),8.0,54.0
8,Product-Producer,C-E(1) C-W(2) E-D(1) E-O(2) I-A(3) _O(9),9.0,53.0
9,Other,C-E(11) C-W(7) C-C(4) E-D(11) E-O(9) I-A(3) M-...,NaN,65.0

# Fold5

In [20]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold5', 'error-analysis/elmo-model/Fold5', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -5.74 	 p_value 0.0004342971033097667
Metric: Recall 	 statistic -1.01 	 p_value 0.3424582760790444
Metric: F1 	 statistic -6.23 	 p_value 0.00025133432978246547

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro 0.17
Metric: Recall 	 Macro-Micro -0.59
Metric: F1 	 Macro-Micro -0.26

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro -0.39
Metric: Recall 	 Macro-Micro -0.41
Metric: F1 	 Macro-Micro -0.46

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -8.01
Metric: Recall 	 Difference -0.79
Metric: F1 	 Difference -4.55

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -8.57
Metric: Recall 	 Difference -0.61
Metric: F1 	 Difference -4.75
Accuracy_Baseline - Accuracy_Elmo -5.00

In [21]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(4) E-O(2) P-P(1) _O(5),5.0,87.0
1,Component-Whole,C-C(3) E-D(1) E-O(1) M-C(1) M-T(3) _O(9),9.0,72.0
2,Content-Container,C-W(5) E-D(3) I-A(1) _O(1),1.0,43.0
3,Entity-Destination,C-C(3) _O(1),1.0,81.0
4,Entity-Origin,C-E(6) C-W(3) I-A(2) _O(2),2.0,59.0
5,Instrument-Agency,C-W(5) C-C(1) E-O(1) P-P(3) _O(5),5.0,36.0
6,Member-Collection,C-W(4) M-T(1) P-P(1) _O(4),4.0,59.0
7,Message-Topic,C-W(1) E-D(2) I-A(1) _O(4),4.0,55.0
8,Product-Producer,C-E(1) C-W(2) C-C(1) E-D(1) E-O(3) I-A(1) _O(6),6.0,56.0
9,Other,C-E(13) C-W(11) C-C(7) E-D(14) E-O(7) I-A(8) M...,NaN,43.0

In [22]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(1) _O(9),9.0,88.0
1,Component-Whole,C-C(2) I-A(1) P-P(1) _O(14),14.0,72.0
2,Content-Container,C-W(2) E-D(2) _O(3),3.0,45.0
3,Entity-Destination,C-C(3) _O(3),3.0,79.0
4,Entity-Origin,C-E(4) _O(8),8.0,60.0
5,Instrument-Agency,C-W(1) M-T(1) P-P(1) _O(11),11.0,37.0
6,Member-Collection,M-T(1) P-P(1) _O(5),5.0,62.0
7,Message-Topic,C-W(1) E-D(1) _O(7),7.0,54.0
8,Product-Producer,C-E(1) E-D(1) E-O(4) I-A(1) _O(9),9.0,55.0
9,Other,C-E(8) C-W(6) C-C(4) E-D(5) E-O(2) I-A(7) M-C(...,NaN,79.0

# Fold6

In [23]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold6', 'error-analysis/elmo-model/Fold6', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -3.78 	 p_value 0.005355326801437347
Metric: Recall 	 statistic -0.01 	 p_value 0.9912022356883525
Metric: F1 	 statistic -2.88 	 p_value 0.020419788465644732

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.70
Metric: Recall 	 Macro-Micro -0.29
Metric: F1 	 Macro-Micro -0.67

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro -0.64
Metric: Recall 	 Macro-Micro -0.42
Metric: F1 	 Macro-Micro -0.75

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -6.58
Metric: Recall 	 Difference -0.02
Metric: F1 	 Difference -3.36

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -6.52
Metric: Recall 	 Difference -0.15
Metric: F1 	 Difference -3.44
Accuracy_Baseline - Accuracy_Elmo -2.51

In [24]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(1) E-O(2) M-T(2) _O(3),3.0,90.0
1,Component-Whole,C-C(4) E-D(1) E-O(1) I-A(5) M-C(2) _O(9),9.0,70.0
2,Content-Container,C-W(1) M-C(1) _O(3),3.0,48.0
3,Entity-Destination,C-C(5) _O(1),1.0,78.0
4,Entity-Origin,C-E(1) M-T(1) P-P(1) _O(2),2.0,66.0
5,Instrument-Agency,C-W(6) E-O(1) P-P(1) _O(5),5.0,36.0
6,Member-Collection,C-W(2) _O(5),5.0,62.0
7,Message-Topic,C-W(2) E-D(1) E-O(1) _O(4),4.0,52.0
8,Product-Producer,C-E(1) C-W(4) E-D(1) E-O(3) I-A(6) M-C(1) _O(6),6.0,49.0
9,Other,C-E(9) C-W(12) C-C(9) E-D(8) E-O(11) I-A(7) M-...,NaN,54.0

In [25]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(1) M-T(1) _O(13),13.0,85.0
1,Component-Whole,C-C(3) I-A(3) M-C(3) _O(16),16.0,69.0
2,Content-Container,C-W(1) E-D(1) M-C(2) _O(4),4.0,45.0
3,Entity-Destination,C-C(2),0.0,82.0
4,Entity-Origin,C-E(1) _O(6),6.0,64.0
5,Instrument-Agency,C-W(1) E-O(1) _O(14),14.0,33.0
6,Member-Collection,C-W(1) C-C(1) _O(4),4.0,63.0
7,Message-Topic,C-W(1) _O(7),7.0,55.0
8,Product-Producer,C-E(1) C-W(1) E-D(1) E-O(2) I-A(2) _O(8),8.0,56.0
9,Other,C-E(8) C-W(7) C-C(5) E-D(8) E-O(9) I-A(4) M-C(...,NaN,73.0

# Fold7

In [26]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold7', 'error-analysis/elmo-model/Fold7', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -4.38 	 p_value 0.0023582012033590994
Metric: Recall 	 statistic 0.43 	 p_value 0.6761077845763279
Metric: F1 	 statistic -2.57 	 p_value 0.033096646111987114

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.25
Metric: Recall 	 Macro-Micro -0.04
Metric: F1 	 Macro-Micro -0.29

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro -0.56
Metric: Recall 	 Macro-Micro -0.08
Metric: F1 	 Macro-Micro -0.45

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -7.94
Metric: Recall 	 Difference 0.81
Metric: F1 	 Difference -3.73

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -8.25
Metric: Recall 	 Difference 0.77
Metric: F1 	 Difference -3.89
Accuracy_Baseline - Accuracy_Elmo -3.66

In [27]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(1) M-T(3) P-P(1) _O(8),8.0,87.0
1,Component-Whole,C-C(5) E-O(2) I-A(3) M-T(2) P-P(1) _O(1),1.0,79.0
2,Content-Container,C-W(2) E-D(1),0.0,50.0
3,Entity-Destination,C-W(1) C-C(4) E-O(1) M-T(3),0.0,75.0
4,Entity-Origin,C-E(1) C-W(2) C-C(1) E-D(1) I-A(1) M-T(1) _O(6),6.0,57.0
5,Instrument-Agency,C-W(3) E-D(1) P-P(2) _O(1),1.0,41.0
6,Member-Collection,C-E(1) C-W(2) C-C(1) M-T(1) _O(2),2.0,61.0
7,Message-Topic,C-W(4) _O(10),10.0,47.0
8,Product-Producer,C-W(1) E-O(3) I-A(1) M-T(2) _O(5),5.0,59.0
9,Other,C-E(6) C-W(18) C-C(6) E-D(7) E-O(13) I-A(7) M-...,NaN,47.0

In [28]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,M-T(1) _O(10),10.0,89.0
1,Component-Whole,C-C(3) E-O(1) I-A(2) M-T(1) _O(9),9.0,77.0
2,Content-Container,C-W(1) E-D(1) _O(2),2.0,49.0
3,Entity-Destination,C-C(2) E-O(1) _O(4),4.0,77.0
4,Entity-Origin,C-E(1) C-W(1) E-D(1) I-A(1) _O(10),10.0,56.0
5,Instrument-Agency,_O(8),8.0,41.0
6,Member-Collection,C-C(1) _O(5),5.0,62.0
7,Message-Topic,C-W(3) _O(8),8.0,51.0
8,Product-Producer,E-O(3) I-A(2) _O(17),17.0,49.0
9,Other,C-E(3) C-W(10) C-C(5) E-D(4) E-O(10) I-A(4) M-...,NaN,81.0

# Fold8

In [29]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold8', 'error-analysis/elmo-model/Fold8', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -6.20 	 p_value 0.00025912256253245603
Metric: Recall 	 statistic -0.38 	 p_value 0.7147810995049206
Metric: F1 	 statistic -4.16 	 p_value 0.003146077168070826

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.51
Metric: Recall 	 Macro-Micro 0.22
Metric: F1 	 Macro-Micro -0.40

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro -0.62
Metric: Recall 	 Macro-Micro -0.12
Metric: F1 	 Macro-Micro -0.45

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -8.89
Metric: Recall 	 Difference -0.73
Metric: F1 	 Difference -5.13

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -9.00
Metric: Recall 	 Difference -1.07
Metric: F1 	 Difference -5.18
Accuracy_Baseline - Accuracy_Elmo -5.68

In [30]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(2) E-O(5) P-P(3) _O(6),6.0,82.0
1,Component-Whole,C-E(1) C-C(2) E-D(1) I-A(5) M-C(4) M-T(3) _O(4),4.0,72.0
2,Content-Container,C-W(1) E-D(2) _O(3),3.0,47.0
3,Entity-Destination,C-C(1) E-O(1) P-P(1),0.0,81.0
4,Entity-Origin,C-E(1) C-C(1) E-D(1) M-C(1) P-P(2) _O(1),1.0,62.0
5,Instrument-Agency,C-W(2) M-T(2) P-P(1) _O(2),2.0,41.0
6,Member-Collection,E-O(1) P-P(1) _O(2),2.0,64.0
7,Message-Topic,C-W(3) I-A(1) _O(6),6.0,52.0
8,Product-Producer,C-W(1) E-D(3) E-O(4) I-A(2) M-C(1) M-T(1) _O(12),12.0,47.0
9,Other,C-E(9) C-W(12) C-C(6) E-D(10) E-O(13) I-A(13) ...,NaN,46.0

In [31]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,C-W(2) E-O(2) P-P(2) _O(7),7.0,86.0
1,Component-Whole,C-C(1) E-D(1) I-A(3) M-C(2) M-T(2) P-P(1) _O(11),11.0,71.0
2,Content-Container,C-W(2) E-D(2) _O(4),4.0,45.0
3,Entity-Destination,C-C(1) E-O(1) _O(1),1.0,81.0
4,Entity-Origin,C-C(1) M-C(1) _O(9),9.0,59.0
5,Instrument-Agency,C-W(1) P-P(1) _O(8),8.0,39.0
6,Member-Collection,E-O(1) _O(3),3.0,64.0
7,Message-Topic,_O(10),10.0,53.0
8,Product-Producer,E-D(1) I-A(1) _O(11),11.0,57.0
9,Other,C-E(6) C-W(6) C-C(6) E-D(6) E-O(6) I-A(6) M-C(...,NaN,84.0

# Fold9

In [32]:
summary_cm_baseline, summary_cm_elmo = print_full_summary(
    'error-analysis/baseline/Fold9', 'error-analysis/elmo-model/Fold9', 
    'Baseline','Elmo', res, relation_full_form_dictionary, relation_as_short_list)

TTest from Baseline to Elmo
Below is the metric comparsion across the two models considering individual relations, excluding 'Other'
Metric: Precision 	 statistic -4.97 	 p_value 0.0010963027236925178
Metric: Recall 	 statistic 1.44 	 p_value 0.1886842969509118
Metric: F1 	 statistic -2.14 	 p_value 0.06457459907797053

All the macro and micro metrics are calculated, excluding the 'Other' class
Macro - Micro for the Baseline model
Metric: Precision 	 Macro-Micro -0.22
Metric: Recall 	 Macro-Micro 0.23
Metric: F1 	 Macro-Micro -0.12

Macro - Micro for the Elmo model
Metric: Precision 	 Macro-Micro -0.42
Metric: Recall 	 Macro-Micro -0.11
Metric: F1 	 Macro-Micro -0.36

Macro_Baseline - Macro_Elmo
Metric: Precision 	 Difference -5.69
Metric: Recall 	 Difference 1.70
Metric: F1 	 Difference -2.23

Micro_Baseline - Micro_Elmo
Metric: Precision 	 Difference -5.89
Metric: Recall 	 Difference 1.36
Metric: F1 	 Difference -2.47
Accuracy_Baseline - Accuracy_Elmo -1.73

In [33]:
summary_cm_baseline

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(5) P-P(2) _O(2),2.0,90.0
1,Component-Whole,C-C(4) E-D(1) E-O(4) I-A(4) M-C(1) M-T(3) P-P(...,4.0,70.0
2,Content-Container,C-W(1) E-D(3) _O(2),2.0,47.0
3,Entity-Destination,C-W(1) C-C(1) M-T(1) _O(1),1.0,81.0
4,Entity-Origin,C-E(4) C-W(1) I-A(1) M-T(1) P-P(3) _O(5),5.0,57.0
5,Instrument-Agency,C-W(1) E-O(1) P-P(1) _O(2),2.0,46.0
6,Member-Collection,C-W(1) C-C(1) E-O(1) P-P(3) _O(2),2.0,60.0
7,Message-Topic,C-E(1) C-W(1) E-O(1) _O(4),4.0,56.0
8,Product-Producer,C-W(3) C-C(1) E-O(3) M-C(1) M-T(1) _O(2),2.0,62.0
9,Other,C-E(6) C-W(14) C-C(5) E-D(10) E-O(13) I-A(11) ...,NaN,46.0

In [34]:
summary_cm_elmo

summary,Gold Relation,Confused With(num_examples),Confused with Other,Correct Predictions
0,Cause-Effect,E-O(5) P-P(1) _O(6),6.0,88.0
1,Component-Whole,C-C(1) E-O(2) I-A(3) M-C(1) M-T(1) P-P(1) _O(12),12.0,71.0
2,Content-Container,C-W(2) E-D(2) _O(4),4.0,46.0
3,Entity-Destination,_O(3),3.0,82.0
4,Entity-Origin,C-E(3) I-A(1) P-P(1) _O(10),10.0,57.0
5,Instrument-Agency,C-W(1) P-P(1) _O(7),7.0,41.0
6,Member-Collection,C-W(1) C-C(1) P-P(1) _O(7),7.0,59.0
7,Message-Topic,C-W(1) E-O(1) _O(5),5.0,57.0
8,Product-Producer,C-W(1) E-O(1) I-A(1) M-C(1) _O(10),10.0,59.0
9,Other,C-E(3) C-W(7) C-C(4) E-D(3) E-O(10) I-A(8) M-C...,NaN,69.0